### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by areebbeigh** [dev-kashmir/dev-kashmir-website#5]
LinkedIn profile links are broken:

- https://kashmiri.dev/devs/bassamismail
- https://kashmiri.dev/devs/haideralipunjabi

**Comment by skippednote** [comment]
Hey @areebbeigh. I can access both the pages. Could you check with caches cleared and service worker unregistered?

**Comment by areebbeigh** [comment]
> Hey @areebbeigh. I can access both the pages. Could you check with caches cleared and service worker unregistered?

Referring to the LinkedIn profiles on those pages. Are those working for you?

**Comment by skippednote** [comment]
@areebbeigh I didn't read it right first. Thanks for the clarification. It should be fixed it now.
